### ISSUE TITLE
Sftp related: EOFError() raised on big files

### ISSUE THREAD

**Issue by adi-** [django-backup/django-backup#12]
That is paramiko/sftp related, but since it is breaking backup files uploads should be taken into account. While I am transfering big files 150MB+ backup scripts quits with raised `EOFError()`.

Traceback:

```
Traceback (most recent call last):
File "/home/user/.virtualenvs/user/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
R = retval = fun(*args, **kwargs)
File "/home/user/.virtualenvs/user/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
return self.run(*args, **kwargs)
File "/srv/user/user/core/tasks.py", line 15, in backup
call_command("backup", compress=True, media=True, clean_media=True, clean_db=True, ftp=True)
File "/home/user/.virtualenvs/user/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
return command.execute(*args, **defaults)
File "/home/user/.virtualenvs/user/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
output = self.handle(*args, **options)
File "/home/user/.virtualenvs/user/src/django-backup-develop/django_backup/management/commands/backup.py", line 129, in handle
self._handle(*args, **kwargs)
File "/home/user/.virtualenvs/user/src/django-backup-develop/django_backup/management/commands/backup.py", line 253, in _handle
self.store_ftp(local_files=[os.path.join(os.getcwd(), x) for x in dir_outfiles + [outfile]])
File "/home/user/.virtualenvs/user/src/django-backup-develop/django_backup/management/commands/backup.py", line 297, in store_ftp
sftp.put(local_file, os.path.join(self.remote_dir or '', filename))
File "/home/user/.virtualenvs/user/local/lib/python2.7/site-packages/pysftp.py", line 349, in put
confirm=confirm)
File "/home/user/.virtualenvs/user/local/lib/python2.7/site-packages/paramiko/sftp_client.py", line 669, in put
return self.putfo(fl, remotepath, file_size, callback, confirm)
File "/home/user/.virtualenvs/user/local/lib/python2.7/site-packages/paramiko/sftp_client.py", line 626, in putfo
fr.write(data)
File "/home/user/.virtualenvs/user/local/lib/python2.7/site-packages/paramiko/file.py", line 339, in write
self._write_all(data)
File "/home/user/.virtualenvs/user/local/lib/python2.7/site-packages/paramiko/file.py", line 456, in _write_all
count = self._write(data)
File "/home/user/.virtualenvs/user/local/lib/python2.7/site-packages/paramiko/sftp_file.py", line 176, in _write
self._reqs.append(self.sftp._async_request(type(None), CMD_WRITE, self.handle, long(self._realpos), data[:chunk]))
File "/home/user/.virtualenvs/user/local/lib/python2.7/site-packages/paramiko/sftp_client.py", line 750, in _async_request
self._send_packet(t, msg)
File "/home/user/.virtualenvs/user/local/lib/python2.7/site-packages/paramiko/sftp.py", line 170, in _send_packet
self._write_all(out)
File "/home/user/.virtualenvs/user/local/lib/python2.7/site-packages/paramiko/sftp.py", line 135, in _write_all
raise EOFError()
EOFError
```

**Comment by andybak** [comment]
Is there anything we can do or does it really need to be reported to paramiko or pysftp?

**Comment by adi-** [comment]
I think they already know about it. But, nothing have been done to fix it, yet. I have seen some pull requests, but none have been merged unfortunately.

Django-backup should know about it, as 100+MB of media folder backups almost concerns everyone. Maybe other sftp library? Maybe a fix to paramico?

Dnia 18.09.2015 o godz. 13:04 Andy Baker notifications@github.com napisał(a):

**Comment by adi-** [comment]
Problem probably occurs when the server is timing you out for inactivity.

**Comment by andybak** [comment]
Inactivity? i.e. the network is down or super-slow?

What should django-backup do in this case? In my setup we get an email alerting us that the job failed (our cron runner does that) and also another service checks the integrity and presence of backups daily.

i.e. we don't solve this via django-backup - it's handled by other parts of our infrastructure.

**Comment by adi-** [comment]
I also get e-mails when it fails, that is how I get all info about the error. I am trying to guess what could be wrong since `File "/home/user/.virtualenvs/user/local/lib/python2.7/site-packages/paramiko/sftp.py", line 135, in _write_all raise EOFError()` isn't very informative.

If paramiko is broken I hope it will be fixed in new versions. If not, there could be something done with it like connection upkeep?
